# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160215_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='title',
            new_name='name',
        ),
    ]
