# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160218_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default',
        ),
    ]
